Repository wecode-bootcamp-korea/18-2nd-Heuream-backend, pull requests merged in 2021-04, with the labels that each got.

#4 [흐림 허정원] 로그인 데코레이터 생성
  account/utils.py
Labels: Status: 리뷰 요청

#3 [긴급][흐림 허정원, 김규동] Modeling 참조키 변경
  account/migrations/0003_auto_20210402_0225.py
  account/migrations/0004_auto_20210402_0841.py
  account/models.py
Labels: Status: 도움 요청, Status: 리뷰 요청

#6 [흐림] Fix: 로그인 데코레이터 예외처리
  account/utils.py
Labels: Status: 리뷰 요청

#5 [흐림 허정원] Refactor 수정사항 변경
  heuream/settings.py
  heuream/urls.py
  product/tests.py
  product/urls.py
  product/views.py
Labels: Status: Review 진행중

#8 [흐림 김규동] Modify : list comprehension 변수명 수정, 가격 소수점 자리수 수정 완료했습니당
  bidding/tests.py
  bidding/urls.py
  bidding/views.py
  heuream/urls.py
Labels: Status: 리뷰 요청

#13 [흐림 김규동] Modify : 로그인 기능 Conflict 해결
  account/tests.py
  account/urls.py
  account/views.py
  heuream/urls.py
Labels: Status: 리뷰 요청

#12 [흐림 김규동] Modify : 회원가입 Conflict 수정 완료
  account/tests.py
  account/urls.py
  account/views.py
  bidding/tests.py
Labels: Status: Accepted

#11 [흐림 김규동] Add : 카카오 회원가입, 로그인 기능 추가, 카카오 회원가입 로그인 테스트 추가 / conflict 해결!
  account/tests.py
  account/urls.py
  account/views.py
  bidding/tests.py
Labels: Status: 리뷰 요청

#9 [흐림 허정원] Wishlist 기능 구현
  heuream/settings.py
  product/tests.py
  product/urls.py
  product/views.py
Labels: Status: 리뷰 요청

#14 [흐림 허정원] SearchView 기능 구현
  product/tests.py
  product/urls.py
  product/views.py
Labels: Status: 리뷰 요청

#15 [흐림 김규동] Add : 상품상세 페이지 구매버튼 누르면 정보주는 뷰 작성 완료
  bidding/tests.py
  bidding/urls.py
  bidding/views.py
Labels: Status: 리뷰 요청

#16 [흐림 김규동] Add : 상품상세 페이지 판매버튼 정보 뷰 작성 완료
  bidding/tests.py
  bidding/urls.py
  bidding/views.py
Labels: Status: 리뷰 요청
